[package]
name = "octoscraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.15", features = ["json"] }
tokio = { version = "1", features = ["full"] }
select = "0.6.0"
num_cpus = "1.15.0"
tempfile="3.4.0"
rand="0.8.5"